name: Install Checker
on: [push, pull_request, workflow_call]
jobs:

    test-python-os-versions:
        name: Check Python ${{ matrix.python-version }} on ${{ matrix.os }} on ${{ matrix.architecture }}
        runs-on: ${{ matrix.os }}
        continue-on-error: ${{ matrix.allow_failure == 'true' }}
        strategy:
            fail-fast: false
            matrix:
                allow_failure: [false]
                os: [ubuntu-latest, windows-latest, macos-latest]
                architecture: [x86_64]
                python-version: ["3.9", "3.10", "3.11"]
                include:
                    - python-version: "3.10"
                    - architecture: [arm64]
                    - runs-on: macos-latest
                      allow_failure: true
        steps:
            - uses: actions/checkout@v3
            
            - name: Setup Python ${{ matrix.python-version }}
              uses: actions/setup-python@v4
              with:
                python-version: ${{ matrix.python-version }}
            - name: Install repo
              run: |
                python -m pip install .
            - name: Check installation
              run: |
                python -c "import py4DSTEM; print(py4DSTEM.__version__)"